version: "3.2"

services:
  db.mysql57.dev.local:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql57_data:/var/lib/mysql
    networks:
      - mysql57-network-local
    ports:
      - "13306:3306"
  adminer.mysql57.dev.local:
    image: adminer:4.8.0
    depends_on:
      - db.mysql57.dev.local
    environment:
      ADMINER_DEFAULT_SERVER: db.mysql57.dev.local
    networks:
      - mysql57-network-local    
    ports:
      - 18080:8080

volumes:
  mysql57_data:

networks: 
  mysql57-network-local:
    driver: bridge