version: "3.8"

services:
  storage.minio-latest.devbox.local:
    image: minio/minio:latest
    environment:
      MINIO_REGION: ${DEVBOX_MINIO_STORAGE_REGION:-us-east-1}
      MINIO_ACCESS_KEY: ${DEVBOX_MINIO_STORAGE_ACCESS_KEY:-AKIAIOSFODNN7EXAMPLE}
      MINIO_SECRET_KEY: ${DEVBOX_MINIO_STORAGE_ACCESS_KEY:-wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY}
    volumes:
      - minio-latest_storage_data:/data
    command: server --address 0.0.0.0:9000 /data
    networks:
      - minio-latest_network_local
    ports:
      - ${DEVBOX_MINIO_STORAGE_EXPORT_PORT:-29000}:9000

volumes:
  minio-latest_storage_data:

networks:
  minio-latest_network_local:
    driver: bridge
