version: "3.8"

services:
  db.mariadb105.dev.local:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mariadb105_data:/var/lib/mysql
    networks:
      - mariadb105_network_local
    ports:
      - 13306:3306
  phpmyadmin.mariadb105.dev.local:
    image: phpmyadmin/phpmyadmin:5
    depends_on:
      - db.mariadb105.dev.local
    environment:
      PMA_HOST: db.mariadb105.dev.local
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - mariadb105_network_local
    ports:
      - 23306:80
  adminer.mariadb105.dev.local:
    image: adminer:4
    depends_on:
      - db.mariadb105.dev.local
    environment:
      ADMINER_DEFAULT_SERVER: db.mariadb105.dev.local
    networks:
      - mariadb105_network_local
    ports:
      - 33306:8080

volumes:
  mariadb105_data:

networks:
  mariadb105_network_local:
    driver: bridge
