version: "3.8"

services:
  zookeeper.kafka61.devbox.local:
    image: confluentinc/cp-zookeeper:6.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - kafka61_zookeeper_data:/data
    networks:
      - kafka61_network_local
    ports:
      - 2181:2181
  broker1.kafka61.devbox.local:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper.kafka61.devbox.local
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker1.kafka61.devbox.local:19092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker1_data:/var/lib/kafka/data
    networks:
      - kafka61_network_local
    ports:
      - 9092:9092
  broker2.kafka61.devbox.local:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper.kafka61.devbox.local
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker2.kafka61.devbox.local:19093,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker2_data:/var/lib/kafka/data
    networks:
      - kafka61_network_local
    ports:
      - 9093:9093
  broker3.kafka61.devbox.local:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper.kafka61.devbox.local
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.kafka61.devbox.local:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker3.kafka61.devbox.local:19094,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
    volumes:
      - kafka61_broker3_data:/var/lib/kafka/data
    networks:
      - kafka61_network_local
    ports:
      - 9094:9094
  kafdrop.kafka61.devbox.local:
    image: obsidiandynamics/kafdrop:3.27.0
    depends_on:
      - broker1.kafka61.devbox.local
      - broker2.kafka61.devbox.local
      - broker3.kafka61.devbox.local
    environment:
      KAFKA_BROKERCONNECT: broker1.kafka61.devbox.local:19092
    networks:
      - kafka61_network_local
    ports:
      - 29000:9000
  kafka-ui.kafka61.devbox.local:
    image: provectuslabs/kafka-ui:0.0.10
    depends_on:
      - broker1.kafka61.devbox.local
      - broker2.kafka61.devbox.local
      - broker3.kafka61.devbox.local
    environment:
      KAFKA_CLUSTERS_0_NAME: broker1.kafka61.devbox.local:19092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker1.kafka61.devbox.local:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper.kafka61.devbox.local:2181
    networks:
      - kafka61_network_local
    ports:
      - 28080:8080

volumes:
  kafka61_zookeeper_data:
  kafka61_broker1_data:
  kafka61_broker2_data:
  kafka61_broker3_data:

networks:
  kafka61_network_local:
    driver: bridge
