version: "3.8"

services:
  db.redis70.devbox.local:
    image: redis:7.0-alpine
    volumes:
      - redis70_db_data:/var/lib/redis
    networks:
      - redis70_network_local
    ports:
      - ${DEVBOX_REDIS70_DB_EXPORT_PORT:-17379}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 2s
      retries: 10
  phpredisadmin.redis70.devbox.local:
    image: erikdubbelboer/phpredisadmin:latest
    depends_on:
      db.redis70.devbox.local:
        condition: service_healthy
    environment:
      REDIS_1_NAME: db.redis70.devbox.local
      REDIS_1_HOST: db.redis70.devbox.local
      REDIS_1_PORT: 6379
    networks:
      - redis70_network_local
    ports:
      - ${DEVBOX_REDIS70_PRA_EXPORT_PORT:-17380}:80
    healthcheck:
      test: ["CMD-SHELL", "curl --connect-timeout 5 -s http://127.0.0.1 > /dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 20
  redis-commander.redis70.devbox.local:
    image: rediscommander/redis-commander:latest
    depends_on:
      db.redis70.devbox.local:
        condition: service_healthy
    environment:
      REDIS_HOSTS: db.redis70.devbox.local:db.redis70.devbox.local:6379
    networks:
      - redis70_network_local
    ports:
      - ${DEVBOX_REDIS70_COMMANDER_EXPORT_PORT:-17381}:8081
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  redis70_db_data:

networks:
  redis70_network_local:
    driver: bridge
