version: "3.8"

services:
  db.mongo44.devbox.local:
    image: mongo:4.4-bionic
    volumes:
      - mongo44_db_data:/data/db
    networks:
      - mongo44_network_local
    ports:
      - ${DEVBOX_MONGO44_DB_EXPORT_PORT:-27017}:27017
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "127.0.0.1/test", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"]
      start_period: 20s
      interval: 10s
      timeout: 10s
      retries: 10
  mongo-express.mongo44.devbox.local:
    image: mongo-express:0.54
    depends_on:
      db.mongo44.devbox.local:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_SERVER: db.mongo44.devbox.local
    networks:
      - mongo44_network_local
    ports:
      - ${DEVBOX_MONGO44_EXPRESS_EXPORT_PORT:-27018}:8081
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8081 || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 10
  dbgate.mongo44.devbox.local:
    image: dbgate/dbgate:latest
    depends_on:
      db.mongo44.devbox.local:
        condition: service_healthy
    environment:
      CONNECTIONS: mongo1
      ENGINE_mongo1: mongo@dbgate-plugin-mongo
      LABEL_mongo1: db.mongo44.devbox.local
      SERVER_mongo1: db.mongo44.devbox.local
      PORT_mongo1: 27017
    networks:
      - mongo44_network_local
    ports:
      - ${DEVBOX_MONGO44_DBGATE_EXPORT_PORT:-27019}:3000
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 3s
      timeout: 10s
      retries: 10
  nosqlclient.mongo44.devbox.local:
    image: mongoclient/mongoclient:4.0.1
    depends_on:
      db.mongo44.devbox.local:
        condition: service_healthy
    environment:
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://db.mongo44.devbox.local:27017
    volumes:
      - mongo44_nosqlclient_data:/data/db
    networks:
      - mongo44_network_local
    ports:
      - ${DEVBOX_MONGO44_NOSQLCLIENT_EXPORT_PORT:-27020}:3000
    healthcheck:
      test: ["CMD-SHELL", "curl --connect-timeout 5 -s http://127.0.0.1:3000 > /dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 60

volumes:
  mongo44_db_data:
  mongo44_nosqlclient_data:

networks:
  mongo44_network_local:
    driver: bridge
